[[colors.indexed_colors]]
color = "#d27e46"  # Tono terracota suave
index = 16

[[colors.indexed_colors]]
color = "#c85552"  # Rojo apagado
index = 17

[colors.bright]
black = "#6f675f"   # Gris c치lido
blue = "#7fa8b8"    # Azul suave
cyan = "#7a9d94"    # Cyan apagado
green = "#8fa876"   # Verde suave
magenta = "#8a7f9a" # Magenta apagado
red = "#d74747"     # Rojo suave
white = "#dcd7ba"   # Beige claro (se mantiene)
yellow = "#d4b073"  # Amarillo suave

[colors.cursor]
cursor = "#c8c093"  # Beige claro (se mantiene)
text = "#c8c093"    # Beige claro (se mantiene)

[colors.normal]
black = "#1f1f1f"   # Negro c치lido
blue = "#6a7e9e"    # Azul apagado
cyan = "#5a8b7f"    # Cyan oscuro suave
green = "#6a8560"   # Verde oscuro suave
magenta = "#7a6a8a" # Magenta oscuro suave
red = "#b44d4d"     # Rojo oscuro suave
white = "#c8c093"   # Beige claro (se mantiene)
yellow = "#b89c5e"  # Amarillo oscuro suave

[colors.primary]
background = "#303030"  # Fondo oscuro c치lido
foreground = "#dcd7ba"  # Beige claro (se mantiene)

[colors.selection]
background = "#3a4a5a"  # Azul gris치ceo apagado
text = "#c8c093"        # Beige claro (se mantiene)

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "Iosevka NF"

[scrolling]
history = 10000
multiplier = 3

[terminal]

[terminal.shell]
program = "/home/estebandev/.tmux/init-session.sh"

[env]
TERM = "xterm-256color"


[window]
padding = { x = 6, y = 9 }
# Uncomment for Windows
#[shell]
#program = "wsl.exe"
#args = ["--cd","~"]

[[keyboard.bindings]]
key = "F"
mods = "Control"
command = { program = "tmux", args = ["split-window", "-h", "bash -c /home/estebandev/.tmux/init-session.sh"] }
